# Generated by Django 5.2.1 on 2025-06-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('hls_master_path', models.URLField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, help_text='z.\u202fB. 1080p, 720p', max_length=20)),
                ('language', models.CharField(default='en', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False, help_text='HLS-Conversion abgeschlossen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='app_videos.video')),
            ],
            options={
                'ordering': ['resolution'],
                'unique_together': {('video', 'resolution', 'language')},
            },
        ),
    ]
