# Generated by Django 5.2.1 on 2025-06-13 23:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Video ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, help_text='Genre des Videos', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Video File ID')),
                ('duration', models.DurationField(blank=True, help_text='Videolänge', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('preview_file', models.FileField(blank=True, help_text='Vorschau-Video', null=True, upload_to='previews/')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('hls_master_path', models.URLField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('es', 'Español'), ('it', 'Italiano')], default='en')),
                ('is_default', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False, help_text='HLS-Conversion abgeschlossen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='app_videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('video', 'language')},
            },
        ),
    ]
