# Generated by Django 5.2.1 on 2025-06-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='processing_started',
            field=models.BooleanField(default=False),
        ),
    ]
