# Generated by Django 5.2.1 on 2025-06-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0002_videofile_duration_videofile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, help_text='Genre des Videos', max_length=100),
        ),
        migrations.AddField(
            model_name='videofile',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Vorschau-Video', null=True, upload_to='previews/'),
        ),
    ]
