# Generated by Django 5.2.1 on 2025-06-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0002_videofile_processing_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='processing_started',
        ),
    ]
