# Generated by Django 5.2.1 on 2025-06-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0003_remove_videofile_processing_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='genre',
        ),
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='videos', to='app_videos.genre', verbose_name='Genres'),
        ),
    ]
