# Generated by Django 5.2.1 on 2025-06-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0005_alter_videofile_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='videofile',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Dauer des Videos in Sekunden'),
        ),
    ]
