# Generated by Django 5.2.1 on 2025-06-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0006_rename_genre_video_genres_alter_videofile_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
    ]
