# Generated by Django 5.2.1 on 2025-06-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0007_rename_genre_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='localized_description',
            field=models.TextField(blank=True, help_text='Description in the specific language'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='localized_title',
            field=models.CharField(blank=True, help_text='Title in the specific language', max_length=255),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='duration',
            field=models.FloatField(default=0.0, help_text='Duration of the video in seconds'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='HLS conversion completed'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Preview video file', null=True, upload_to='previews/'),
        ),
    ]
