# Generated by Django 5.2.1 on 2025-06-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0008_videofile_localized_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='is_default',
        ),
    ]
