# Generated by Django 5.2.1 on 2025-06-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0009_remove_videofile_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='hls_master_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
