# Generated by Django 5.2.1 on 2025-07-30 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_userprofiles_preferred_language'),
        ('app_videos', '0010_alter_videofile_hls_master_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.FloatField(default=0.0, help_text='Current playback position in seconds', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Progress as percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_completed', models.BooleanField(default=False)),
                ('is_started', models.BooleanField(default=False)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='app_users.userprofiles')),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='app_videos.videofile')),
            ],
            options={
                'ordering': ['-last_watched'],
                'unique_together': {('profile', 'video_file')},
            },
        ),
    ]
