# Generated by Django 5.2.1 on 2025-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_videos', '0011_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='completion_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='first_watched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='total_watch_time',
            field=models.FloatField(default=0.0),
        ),
    ]
