# Generated by Django 5.2.1 on 2025-05-21 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_rename_userprofile_userprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='email_verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='password_reset_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='password_reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
