# Generated by Django 5.2.1 on 2025-05-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_customusermodel_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email_verification_token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='password_reset_token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
