# Generated by Django 5.2.1 on 2025-07-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_customusermodel_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10, verbose_name='Preferred language'),
        ),
    ]
